# INDEX PAGE # 
title = "Markdown to Tufte"
subtitle = "*It can scarcely be denied that the supreme goal of all theory is to make the irreducible basic elements as simple and as few as possible without having to surrender the adequate representation of a single datum of experience.*"
baseurl = ""

# PATHS #

# Path to all images
images = "examples/images"
# Path to all markdown
files = "examples/chapters"

# POSTS #

# Posts in the order they will appear 
[[post]]
filename = "chapter1.md"
title = "Chapter 1"
subtitle = "November 1st, 2017"
show = true
slug = "the-first-chapter"


[[post]]
filename = "chapter2.md"
title = "Chapter 2"
subtitle = "November 1st, 2017"
show = true
slug = "chapter2"


[[post]]
filename = "chapter3.md"
title = "Chapter 3"
subtitle = "November 1st, 2017"
show = true
slug = "the-last-chapter/final"

