##### INDEX PAGE ####

title = "markdown2tufte"
subtitle = "*The point of the essay is to change things.* - Edward Tufte"
baseurl = ""

#### PATHS ####

# These paths should be relative to to where you run
# markdown2tufte

# Path to all images
images = "images"

# Path to all markdown
files = "chapters"

#### POSTS ####

# Posts will appear in the order they are 
# set here
# 'slug' is an optional parameter (defaults to filename)

[[post]]
filename = "README.md"
title = "Getting started"
subtitle = "Read me first."

[[post]]
filename = "chapter1.md"
title = "Chapter 1"
subtitle = "November 1st, 2017"

[[post]]
filename = "chapter2.md"
title = "Chapter 2"
subtitle = "November 1st, 2017"

[[post]]
filename = "chapter3.md"
title = "Chapter 3"
subtitle = "November 1st, 2017"
slug = "the-last-chapter/final"

